FROM node:18-alpine

WORKDIR /usr/src/app

# Install Python and other dependencies needed for canvas and sharp
RUN apk add --no-cache \
    python3 \
    build-base \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    musl \
    libc6-compat \
    curl

# Set yarn cache folder
RUN yarn config set cache-folder /usr/src/app/.yarn-cache

# Copy package.json and install dependencies
COPY package*.json ./

RUN yarn

# Copy the rest of the application
COPY . .

COPY ./scripts /usr/src/app/

RUN chmod +x /usr/src/app/scripts/start.sh


# Command run applycation
CMD ["sh", "-c", "/usr/src/app/scripts/start.sh && yarn dev"]

