version: "3.8"

services:
  service:
    container_name: service_media_api
    restart: always
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.dev
    environment:
      NODE_ENV: DEV
      NODE_OPTIONS: "--max-old-space-size=512"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./src:/usr/src/app/src:ro"
    env_file:
      - .env
    networks:
      - service_media-network
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "sh",
    #       "-c",
    #       "curl -sSf http://${NODE_HOST}:${PORT_PRIVATE}/api/v1 > /dev/null",
    #     ]
    #   interval: 60s
    #   timeout: 2s
    #   retries: 3

###* NETWORD GENERAL ###
networks:
  media-network:
    driver: bridge
